/* This code is generated by pOt. */

#include <pOtRTL.h>

#include "Strings.hi"




static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
  pOt_NIL
}};
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
  pOt_NIL
}};




extern pOt_LONGINT pOt_Length_Strings
#if pOt__ANSI_C
  (pOt__DynArr *pOt_s)
#else
  (pOt_s)
  pOt__DynArr *pOt_s;

#endif
{
  pOt_LONGINT pOt__retval;
  pOt_LONGINT pOt_l;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;

  pOt_l=(pOt_LONGINT)(0);
  for(;;) {
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_l)))))!=(unsigned char)'\0')); else break;
    pOt_l+=(1);
  }
  pOt__retval =(pOt_LONGINT)(pOt_l);
  goto pOt__Epilogue;

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  pOt__rm_par((pOt__TypDsc**)pOt_s);
  return pOt__retval;
}




extern void pOt_Append_Strings
#if pOt__ANSI_C
  (pOt__DynArr *pOt_s, pOt__DynArr *pOt_tail)
#else
  (pOt_s, pOt_tail)
  pOt__DynArr *pOt_s;
  pOt__DynArr *pOt_tail;

#endif
{
  pOt_LONGINT pOt_i, pOt_j;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_i=(pOt_LONGINT)(0);
  for(;;) {
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))!=(unsigned char)'\0')); else break;
    pOt_i+=(1);
  }
  pOt_j=(pOt_LONGINT)(pOt_i);
  for(;;) {
    (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))=(*((pOt_CHAR*)(((char *)pOt_tail+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_tail))->nofel,(pOt_LONGINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(pOt_j),6))))));
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)'\0')) {
      goto pOt__LoopLabel_1;
    }
    pOt_i+=(1);
  }
pOt__LoopLabel_1:;

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  pOt__rm_par((pOt__TypDsc**)pOt_tail);
}



static pOt_LONGINT (*pOt_li_FromLInt_Strings);
static pOt_SHORTINT (*pOt_Base_FromLInt_Strings);
static pOt__DynArr *pOt_s_FromLInt_Strings;
static pOt_INTEGER (*pOt_i_FromLInt_Strings);

extern void pOt_FromLInt_Strings pOt__ARGS((pOt_LONGINT , pOt_SHORTINT , pOt__DynArr *));




static void pOt_Tail_FromLInt_Strings
#if pOt__ANSI_C
  (pOt_LONGINT pOt_li)
#else
  (pOt_li)
  pOt_LONGINT pOt_li;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  if(( pOt_li>=((pOt_LONGINT)((*pOt_Base_FromLInt_Strings))))) {
    pOt_Tail_FromLInt_Strings((pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_li),(pOt_LONGINT)((*pOt_Base_FromLInt_Strings)),6)));
    pOt_li=(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_li),(pOt_LONGINT)((*pOt_Base_FromLInt_Strings)),6));
  }
  if(( pOt_li<((pOt_LONGINT)(10)))) {
    (*((pOt_CHAR*)(((char *)pOt_s_FromLInt_Strings+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s_FromLInt_Strings))->nofel,(*pOt_i_FromLInt_Strings))))))=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_li),(pOt_LONGINT)(48),6)));
  } else {
    (*((pOt_CHAR*)(((char *)pOt_s_FromLInt_Strings+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s_FromLInt_Strings))->nofel,(*pOt_i_FromLInt_Strings))))))=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_li),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(65),6)));
  }
  (*pOt_i_FromLInt_Strings)+=(1);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

extern void pOt_FromLInt_Strings
#if pOt__ANSI_C
  (pOt_LONGINT pOt_li, pOt_SHORTINT pOt_Base, pOt__DynArr *pOt_s)
#else
  (pOt_li, pOt_Base, pOt_s)
  pOt_LONGINT pOt_li;
  pOt_SHORTINT pOt_Base;
  pOt__DynArr *pOt_s;

#endif
{
  pOt_LONGINT (*pOt_li_);
  pOt_SHORTINT (*pOt_Base_);
  pOt__DynArr *pOt_s_;
  pOt_INTEGER pOt_i, (*pOt_i_);
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt_li_=pOt_li_FromLInt_Strings;
  pOt_li_FromLInt_Strings=&pOt_li;
  pOt_Base_=pOt_Base_FromLInt_Strings;
  pOt_Base_FromLInt_Strings=&pOt_Base;
  pOt_s_=pOt_s_FromLInt_Strings;
  pOt_s_FromLInt_Strings=pOt_s;
  pOt_i_=pOt_i_FromLInt_Strings;
  pOt_i_FromLInt_Strings=&pOt_i;

  pOt_i=(pOt_INTEGER)(0);
  if(( pOt_li<((pOt_LONGINT)(0)))) {
    if(( pOt_Base==10)) {
      (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,0)))))='-';
      pOt_li=(pOt_LONGINT)(-pOt_li);
      pOt_i=(pOt_INTEGER)(1);
    } else {
      pOt_Tail_FromLInt_Strings((pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(2147483647L),(pOt_LONGINT)(((pOt_SHORTINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_Base),(pOt_LONGINT)(2),4))),6)),(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_li),(pOt_LONGINT)(pOt_Base),6))),(pOt_LONGINT)(pOt_Base),6)),6)));
      pOt_li=(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_li),(pOt_LONGINT)(pOt_Base),6));
    }
  }
  pOt_Tail_FromLInt_Strings((pOt_LONGINT)(pOt_li));
  (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))='\0';

pOt__Epilogue:;
  pOt_li_FromLInt_Strings=pOt_li_;
  pOt_Base_FromLInt_Strings=pOt_Base_;
  pOt_s_FromLInt_Strings=pOt_s_;
  pOt_i_FromLInt_Strings=pOt_i_;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

void pOt_Strings__body()
{
  static int pOt_Strings__loaded=0;
  if(!pOt_Strings__loaded){
    pOt_Strings__loaded=1;


    pOt__gc_ptrs.next=pOt__gc_root;
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;



  pOt__Epilogue:;
  }
}
