/* This code is generated by pOt. */

#include <pOtRTL.h>
#include "Files.h"
#include "Reals.h"

#include "Texts.hi"

typedef pOt_File_Files pOt_Text_Texts;
typedef struct pOt__tag_1_Texts *pOt_Buffer_Texts;
typedef struct pOt__tag_1_Texts pOt_BufDesc_Texts;
typedef struct pOt__tag_2_Texts pOt_Reader_Texts;
typedef struct pOt__tag_4_Texts pOt_Scanner_Texts;
typedef struct pOt__tag_5_Texts pOt_Writer_Texts;

struct pOt__tag_0_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x200L];
} ;
pOt__ArrTypDsc pOt__td_0_Texts= {
  1,
  0x200L, sizeof(pOt_CHAR)
};
struct pOt__tag_1_Texts {
  pOt__RecTypDsc *td;
  pOt_Buffer_Texts pOt_next;
  pOt_LONGINT pOt_len;
  struct pOt__tag_0_Texts pOt_data;
} ;
struct {
  pOt_INTEGER mode;
  pOt_LONGINT size;
  pOt_INTEGER extlev, nstr, nptr, npro;
  pOt__RecTypDsc *base_td[pOt__MaxExts];
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x2];
} pOt__td_1_Texts= {
  0,
  sizeof(struct pOt__tag_1_Texts),
  0x0, 0x1, 0x1, 0x0,
  {pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
  {
    {(pOt_LONGINT)&((struct pOt__tag_1_Texts*)0)->pOt_data, (pOt__TypDsc*)&pOt__td_0_Texts},
    {(pOt_LONGINT)&((struct pOt__tag_1_Texts*)0)->pOt_next, pOt_NIL}
  }
};
struct pOt__tag_2_Texts {
  struct pOt__tag_2_Files base;
  pOt_BOOLEAN pOt_eot;
} ;
struct {
  pOt_INTEGER mode;
  pOt_LONGINT size;
  pOt_INTEGER extlev, nstr, nptr, npro;
  pOt__RecTypDsc *base_td[pOt__MaxExts];
} pOt__td_2_Texts= {
  0,
  sizeof(struct pOt__tag_2_Texts),
  0x1, 0x0, 0x0, 0x0,
  {(pOt__RecTypDsc*)&pOt__td_2_Files, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL}
};
struct pOt__tag_3_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x20L];
} ;
pOt__ArrTypDsc pOt__td_3_Texts= {
  1,
  0x20L, sizeof(pOt_CHAR)
};
struct pOt__tag_4_Texts {
  struct pOt__tag_2_Texts base;
  pOt_CHAR pOt_nextCh;
  pOt_INTEGER pOt_line, pOt_class;
  pOt_LONGINT pOt_i;
  pOt_REAL pOt_x;
  pOt_LONGREAL pOt_y;
  pOt_CHAR pOt_c;
  pOt_SHORTINT pOt_len;
  struct pOt__tag_3_Texts pOt_s;
} ;
struct {
  pOt_INTEGER mode;
  pOt_LONGINT size;
  pOt_INTEGER extlev, nstr, nptr, npro;
  pOt__RecTypDsc *base_td[pOt__MaxExts];
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x1];
} pOt__td_4_Texts= {
  0,
  sizeof(struct pOt__tag_4_Texts),
  0x2, 0x1, 0x0, 0x0,
  {(pOt__RecTypDsc*)&pOt__td_2_Files, (pOt__RecTypDsc*)&pOt__td_2_Texts, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
  {
    {(pOt_LONGINT)&((struct pOt__tag_4_Texts*)0)->pOt_s, (pOt__TypDsc*)&pOt__td_3_Texts}
  }
};
struct pOt__tag_5_Texts {
  pOt__RecTypDsc *td;
  pOt_Buffer_Texts pOt_buf;
} ;
struct {
  pOt_INTEGER mode;
  pOt_LONGINT size;
  pOt_INTEGER extlev, nstr, nptr, npro;
  pOt__RecTypDsc *base_td[pOt__MaxExts];
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x1];
} pOt__td_5_Texts= {
  0,
  sizeof(struct pOt__tag_5_Texts),
  0x0, 0x0, 0x1, 0x0,
  {pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
  {
    {(pOt_LONGINT)&((struct pOt__tag_5_Texts*)0)->pOt_buf, pOt_NIL}
  }
};


static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
  pOt_NIL
}};
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
  pOt_NIL
}};




static void pOt_RdString_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Files *pOt_r, pOt__DynArr *pOt_s)
#else
  (pOt_r, pOt_s)
  struct pOt__tag_2_Files *pOt_r;
  pOt__DynArr *pOt_s;

#endif
{
  pOt_INTEGER pOt_i;
  pOt_CHAR pOt_ch;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_i=(pOt_INTEGER)(0);
  for(;;) {
    pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_ch);
    (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))=pOt_ch;
    pOt_i+=(1);
    if(((((unsigned char)pOt_ch==(unsigned char)'\0'))||((((pOt_LONGINT)(pOt_i))==(*((pOt__ArrTypDsc**)&(*pOt_s)+0))->nofel)))) break;
  }
  for(;;) {
    if((!(*pOt_r).pOt_eof&&(((unsigned char)pOt_ch!=(unsigned char)'\0')))); else break;
    pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_ch);
  }
  (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))='\0';

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




static void pOt_RdInt_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Files *pOt_r, pOt_INTEGER *pOt_n)
#else
  (pOt_r, pOt_n)
  struct pOt__tag_2_Files *pOt_r;
  pOt_INTEGER *pOt_n;

#endif
{
  pOt_CHAR pOt_c0;
  pOt_SHORTINT pOt_s1;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c0);
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_s1);
  (*pOt_n)=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_SHORTINT)(pOt_s1)),(pOt_LONGINT)(256),5)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c0)),5));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




static void pOt_RdLong_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Files *pOt_r, pOt_LONGINT *pOt_n)
#else
  (pOt_r, pOt_n)
  struct pOt__tag_2_Files *pOt_r;
  pOt_LONGINT *pOt_n;

#endif
{
  pOt_CHAR pOt_c0, pOt_c1, pOt_c2;
  pOt_SHORTINT pOt_s3;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c0);
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c1);
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c2);
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_s3);
  (*pOt_n)=(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_SHORTINT)(pOt_s3)),(pOt_LONGINT)(256),5)),(pOt_LONGINT)((pOt_INTEGER)((pOt_INTEGER)((unsigned char)pOt_c2))),6))),(pOt_LONGINT)(256),6)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c1)),6))),(pOt_LONGINT)(256),6)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c0)),6));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




static void pOt_WrtString_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Files *pOt_r, pOt__DynArr *pOt_s)
#else
  (pOt_r, pOt_s)
  struct pOt__tag_2_Files *pOt_r;
  pOt__DynArr *pOt_s;

#endif
{
  pOt_INTEGER pOt_i;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_i=(pOt_INTEGER)(0);
  for(;;) {
    pOt_i+=(1);
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)'\0')) break;
  }
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&(*pOt_r),pOt__make_byte_arr((void*)&(*pOt_s),1,0),(pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(1),5)));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




static void pOt_WrtInt_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Files *pOt_r, pOt_INTEGER pOt_n)
#else
  (pOt_r, pOt_n)
  struct pOt__tag_2_Files *pOt_r;
  pOt_INTEGER pOt_n;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),5))));
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_INTEGER)pOt__rngchk_si(__FILE__,__LINE__,(pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),5)));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




static void pOt_WrtLong_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Files *pOt_r, pOt_LONGINT pOt_n)
#else
  (pOt_r, pOt_n)
  struct pOt__tag_2_Files *pOt_r;
  pOt_LONGINT pOt_n;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),6))));
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),6)),(pOt_LONGINT)(256),6))));
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(65536L),6)),(pOt_LONGINT)(256),6))));
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_INTEGER)pOt__rngchk_si(__FILE__,__LINE__,(pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(16777216L),6)))));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_OpenBuf_Texts
#if pOt__ANSI_C
  (pOt_Buffer_Texts *pOt_B)
#else
  (pOt_B)
  pOt_Buffer_Texts *pOt_B;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&(*pOt_B),(pOt__TypDsc*)&pOt__td_1_Texts);
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_next=(struct pOt__tag_1_Texts*)(pOt_NIL);
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len=(pOt_LONGINT)(0);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



static pOt_File_Files (*pOt_T_Append_Texts);
static pOt_Buffer_Texts *pOt_B_Append_Texts;
static struct pOt__tag_2_Files (*pOt_R_Append_Texts);

extern void pOt_Append_Texts pOt__ARGS((pOt_File_Files , pOt_Buffer_Texts *));




static void pOt_Invert_Append_Texts()
{
  pOt_Buffer_Texts pOt_b1, pOt_b2;
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
  struct {void *next, *vars[0x1];} pOt__gc_strs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__gc_strs.next = &pOt__gc_ptrs;
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
  pOt__gc_strs.vars[0x0]=pOt_NIL;
  pOt__gc_ptrs.vars[0x1]=&pOt_b1;
  pOt__gc_ptrs.vars[0x0]=&pOt_b2;
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
  pOt_b1=pOt_NIL;
  pOt_b2=pOt_NIL;

  pOt_b1=(struct pOt__tag_1_Texts*)(pOt_NIL);
  for(;;) {
    pOt_b2=(struct pOt__tag_1_Texts*)(pOt_b1);
    pOt_b1=(struct pOt__tag_1_Texts*)((*pOt_B_Append_Texts));
    (*pOt_B_Append_Texts)=(struct pOt__tag_1_Texts*)((*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B_Append_Texts)))).pOt_next);
    (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,pOt_b1))).pOt_next=(struct pOt__tag_1_Texts*)(pOt_b2);
    if(( (*pOt_B_Append_Texts)==pOt_NIL)) break;
  }
  (*pOt_B_Append_Texts)=(struct pOt__tag_1_Texts*)(pOt_b1);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

extern void pOt_Append_Texts
#if pOt__ANSI_C
  (pOt_File_Files pOt_T, pOt_Buffer_Texts *pOt_B)
#else
  (pOt_T, pOt_B)
  pOt_File_Files pOt_T;
  pOt_Buffer_Texts *pOt_B;

#endif
{
  pOt_File_Files (*pOt_T_);
  pOt_Buffer_Texts *pOt_B_;
  struct pOt__tag_2_Files pOt_R, (*pOt_R_);
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
  struct {void *next, *vars[0x2];} pOt__gc_strs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__gc_strs.next = &pOt__gc_ptrs;
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
  pOt__gc_strs.vars[0x1]=pOt_NIL;
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
  pOt__gc_strs.vars[0x0]=&pOt_R;
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
  pOt_T_=pOt_T_Append_Texts;
  pOt_T_Append_Texts=&pOt_T;
  pOt_B_=pOt_B_Append_Texts;
  pOt_B_Append_Texts=pOt_B;
  pOt_R_=pOt_R_Append_Texts;
  pOt_R_Append_Texts=&pOt_R;
  pOt__init_var((pOt__TypDsc**)&pOt_R,(pOt__TypDsc*)&pOt__td_2_Files);

  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_R,(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_Length_Files((struct pOt__tag_1_Files*)(pOt_T))));
  pOt_Invert_Append_Texts();
  for(;;) {
    if(( (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len==((pOt_LONGINT)(0)))) {
      goto pOt__LoopLabel_1;
    }
    pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_R,pOt__make_byte_arr((void*)&(*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_data,1,0),(pOt_LONGINT)((*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len));
    if(( (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_next==pOt_NIL)) {
      (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len=(pOt_LONGINT)(0);
      goto pOt__LoopLabel_1;
    }
    (*pOt_B)=(struct pOt__tag_1_Texts*)((*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_next);
  }
pOt__LoopLabel_1:;
  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_R,(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_Pos_Files((struct pOt__tag_2_Files*)&pOt_R)));

pOt__Epilogue:;
  pOt_T_Append_Texts=pOt_T_;
  pOt_B_Append_Texts=pOt_B_;
  pOt_R_Append_Texts=pOt_R_;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_OpenReader_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Texts *pOt_R, pOt_File_Files pOt_T, pOt_LONGINT pOt_pos)
#else
  (pOt_R, pOt_T, pOt_pos)
  struct pOt__tag_2_Texts *pOt_R;
  pOt_File_Files pOt_T;
  pOt_LONGINT pOt_pos;

#endif
{
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
  struct {void *next, *vars[0x1];} pOt__gc_strs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__gc_strs.next = &pOt__gc_ptrs;
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
  pOt__gc_strs.vars[0x0]=pOt_NIL;
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;

  pOt_Set_Files((struct pOt__tag_2_Files*)&(*pOt_R),(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_pos));
  (*pOt_R).pOt_eot=(pOt_BOOLEAN)0;

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_Read_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Texts *pOt_R, pOt_CHAR *pOt_ch)
#else
  (pOt_R, pOt_ch)
  struct pOt__tag_2_Texts *pOt_R;
  pOt_CHAR *pOt_ch;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_R),(pOt_BYTE_SYSTEM*)&(*pOt_ch));
  (*pOt_R).pOt_eot=((*pOt_R).base.pOt_eof||(((unsigned char)(*pOt_ch)==(unsigned char)'\0')));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern pOt_LONGINT pOt_Pos_Texts
#if pOt__ANSI_C
  (struct pOt__tag_2_Texts *pOt_R)
#else
  (pOt_R)
  struct pOt__tag_2_Texts *pOt_R;

#endif
{
  pOt_LONGINT pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;

  pOt__retval =(pOt_LONGINT)(pOt_Pos_Files((struct pOt__tag_2_Files*)&(*pOt_R)));
  goto pOt__Epilogue;

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern void pOt_OpenScanner_Texts
#if pOt__ANSI_C
  (struct pOt__tag_4_Texts *pOt_S, pOt_File_Files pOt_T, pOt_LONGINT pOt_pos)
#else
  (pOt_S, pOt_T, pOt_pos)
  struct pOt__tag_4_Texts *pOt_S;
  pOt_File_Files pOt_T;
  pOt_LONGINT pOt_pos;

#endif
{
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
  struct {void *next, *vars[0x1];} pOt__gc_strs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__gc_strs.next = &pOt__gc_ptrs;
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
  pOt__gc_strs.vars[0x0]=pOt_NIL;
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;

  pOt_OpenReader_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_pos));
  (*pOt_S).pOt_line=(pOt_INTEGER)(0);
  (*pOt_S).pOt_nextCh=' ';

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_6_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x20L];
} ;
static pOt__ArrTypDsc pOt__td_6_Texts= {
  1,
  0x20L, sizeof(pOt_CHAR)
};

static struct pOt__tag_4_Texts *pOt_S_Scan_Texts;
static pOt_CHAR (*pOt_ch_Scan_Texts), (*pOt_term_Scan_Texts);
static pOt_BOOLEAN (*pOt_neg_Scan_Texts), (*pOt_negE_Scan_Texts), (*pOt_hex_Scan_Texts);
static pOt_SHORTINT (*pOt_i_Scan_Texts), (*pOt_j_Scan_Texts), (*pOt_h_Scan_Texts);
static pOt_INTEGER (*pOt_e_Scan_Texts);
static pOt_LONGINT (*pOt_k_Scan_Texts);
static pOt_REAL (*pOt_x_Scan_Texts), (*pOt_f_Scan_Texts);
static pOt_LONGREAL (*pOt_y_Scan_Texts), (*pOt_g_Scan_Texts);
static struct pOt__tag_6_Texts (*pOt_d_Scan_Texts);

extern void pOt_Scan_Texts pOt__ARGS((struct pOt__tag_4_Texts *));




static void pOt_ReadScaleFactor_Scan_Texts()
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
  if(((unsigned char) (*pOt_ch_Scan_Texts)==(unsigned char)'-')) {
    (*pOt_negE_Scan_Texts)=(pOt_BOOLEAN)1;
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
  } else {
    (*pOt_negE_Scan_Texts)=(pOt_BOOLEAN)0;
    if(((unsigned char) (*pOt_ch_Scan_Texts)==(unsigned char)'+')) {
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
    }
  }
  for(;;) {
    if(((((unsigned char)'0'<=(unsigned char)(*pOt_ch_Scan_Texts)))&&(((unsigned char)(*pOt_ch_Scan_Texts)<=(unsigned char)'9')))); else break;
    (*pOt_e_Scan_Texts)=(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((*pOt_e_Scan_Texts)),(pOt_LONGINT)(10),5)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)(*pOt_ch_Scan_Texts))),5)),(pOt_LONGINT)(48),5));
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

extern void pOt_Scan_Texts
#if pOt__ANSI_C
  (struct pOt__tag_4_Texts *pOt_S)
#else
  (pOt_S)
  struct pOt__tag_4_Texts *pOt_S;

#endif
{
  struct pOt__tag_4_Texts *pOt_S_;
  pOt_CHAR pOt_ch, (*pOt_ch_), pOt_term, (*pOt_term_);
  pOt_BOOLEAN pOt_neg, (*pOt_neg_), pOt_negE, (*pOt_negE_), pOt_hex, (*pOt_hex_);
  pOt_SHORTINT pOt_i, (*pOt_i_), pOt_j, (*pOt_j_), pOt_h, (*pOt_h_);
  pOt_INTEGER pOt_e, (*pOt_e_);
  pOt_LONGINT pOt_k, (*pOt_k_);
  pOt_REAL pOt_x, (*pOt_x_), pOt_f, (*pOt_f_);
  pOt_LONGREAL pOt_y, (*pOt_y_), pOt_g, (*pOt_g_);
  struct pOt__tag_6_Texts pOt_d, (*pOt_d_);
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt_S_=pOt_S_Scan_Texts;
  pOt_S_Scan_Texts=pOt_S;
  pOt_ch_=pOt_ch_Scan_Texts;
  pOt_ch_Scan_Texts=&pOt_ch;
  pOt_term_=pOt_term_Scan_Texts;
  pOt_term_Scan_Texts=&pOt_term;
  pOt_neg_=pOt_neg_Scan_Texts;
  pOt_neg_Scan_Texts=&pOt_neg;
  pOt_negE_=pOt_negE_Scan_Texts;
  pOt_negE_Scan_Texts=&pOt_negE;
  pOt_hex_=pOt_hex_Scan_Texts;
  pOt_hex_Scan_Texts=&pOt_hex;
  pOt_i_=pOt_i_Scan_Texts;
  pOt_i_Scan_Texts=&pOt_i;
  pOt_j_=pOt_j_Scan_Texts;
  pOt_j_Scan_Texts=&pOt_j;
  pOt_h_=pOt_h_Scan_Texts;
  pOt_h_Scan_Texts=&pOt_h;
  pOt_e_=pOt_e_Scan_Texts;
  pOt_e_Scan_Texts=&pOt_e;
  pOt_k_=pOt_k_Scan_Texts;
  pOt_k_Scan_Texts=&pOt_k;
  pOt_x_=pOt_x_Scan_Texts;
  pOt_x_Scan_Texts=&pOt_x;
  pOt_f_=pOt_f_Scan_Texts;
  pOt_f_Scan_Texts=&pOt_f;
  pOt_y_=pOt_y_Scan_Texts;
  pOt_y_Scan_Texts=&pOt_y;
  pOt_g_=pOt_g_Scan_Texts;
  pOt_g_Scan_Texts=&pOt_g;
  pOt_d_=pOt_d_Scan_Texts;
  pOt_d_Scan_Texts=&pOt_d;
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_6_Texts);

  pOt_ch=(*pOt_S).pOt_nextCh;
  pOt_i=0;
  for(;;) {
    if(((unsigned char) pOt_ch==(unsigned char)'\12')) {
      (*pOt_S).pOt_line+=(1);
    } else if(((((unsigned char)pOt_ch!=(unsigned char)' '))&&(((unsigned char)pOt_ch!=(unsigned char)'\11')))) {
      goto pOt__LoopLabel_1;
    }
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
  }
pOt__LoopLabel_1:;
  if(((((unsigned char)'A'<=(unsigned char)pOt__cap((unsigned char)pOt_ch)))&&(((unsigned char)pOt__cap((unsigned char)pOt_ch)<=(unsigned char)'Z')))) {
    for(;;) {
      (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
      pOt_i+=(1);
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
      if(((((((unsigned char)pOt__cap((unsigned char)pOt_ch)>(unsigned char)'Z'))||((((unsigned char)'A'>(unsigned char)pOt__cap((unsigned char)pOt_ch)))&&(((unsigned char)pOt_ch>(unsigned char)'9'))))||((((unsigned char)'0'>(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch!=(unsigned char)'.'))))||((pOt_i==31)))) break;
    }
    (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]='\0';
    (*pOt_S).pOt_len=pOt_i;
    (*pOt_S).pOt_class=(pOt_INTEGER)(1);
  } else if(((unsigned char) pOt_ch==(unsigned char)'\"')) {
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
    for(;;) {
      if((((((unsigned char)pOt_ch!=(unsigned char)'\"'))&&(((unsigned char)pOt_ch>=(unsigned char)' ')))&&((pOt_i!=31)))); else break;
      (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
      pOt_i+=(1);
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
    }
    (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]='\0';
    (*pOt_S).pOt_len=(pOt_SHORTINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(1),4);
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
    (*pOt_S).pOt_class=(pOt_INTEGER)(2);
  } else {
    if(((unsigned char) pOt_ch==(unsigned char)'-')) {
      pOt_neg=(pOt_BOOLEAN)1;
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
    } else {
      pOt_neg=(pOt_BOOLEAN)0;
    }
    if(((((unsigned char)'0'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'9')))) {
      pOt_hex=(pOt_BOOLEAN)0;
      pOt_j=0;
      for(;;) {
        pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
        pOt_i+=(1);
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
        if(((unsigned char) pOt_ch<(unsigned char)'0')) {
          goto pOt__LoopLabel_2;
        }
        if(((unsigned char) '9'<(unsigned char)pOt_ch)) {
          if(((((unsigned char)'A'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'F')))) {
            pOt_hex=(pOt_BOOLEAN)1;
            pOt_ch=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_ch)),(pOt_LONGINT)(7),5)));
          } else if(((((unsigned char)'a'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'f')))) {
            pOt_hex=(pOt_BOOLEAN)1;
            pOt_ch=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_ch)),(pOt_LONGINT)(39),5)));
          } else {
            goto pOt__LoopLabel_2;
          }
        }
      }
    pOt__LoopLabel_2:;
      if(((unsigned char) pOt_ch==(unsigned char)'H')) {
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
        (*pOt_S).pOt_class=(pOt_INTEGER)(3);
        if(( (pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(pOt_j),4)>8)) {
          pOt_j=(pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(8),4);
        }
        pOt_k=(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5));
        pOt_j+=(1);
        if(((((pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(pOt_j),4)==7))&&((pOt_k>=((pOt_LONGINT)(8)))))) {
          pOt_k-=(16);
        }
        for(;;) {
          if(( pOt_j<pOt_i)); else break;
          pOt_k=(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(16),6)),(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))),6));
          pOt_j+=(1);
        }
        if(pOt_neg) {
          (*pOt_S).pOt_i=(pOt_LONGINT)(-pOt_k);
        } else {
          (*pOt_S).pOt_i=(pOt_LONGINT)(pOt_k);
        }
      } else if(((unsigned char) pOt_ch==(unsigned char)'.')) {
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
        pOt_h=pOt_i;
        for(;;) {
          if(((((unsigned char)'0'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'9')))); else break;
          pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
          pOt_i+=(1);
          pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
        }
        if(((unsigned char) pOt_ch==(unsigned char)'D')) {
          pOt_e=(pOt_INTEGER)(0);
          pOt_y=(pOt_LONGREAL)(0);
          pOt_g=(pOt_LONGREAL)(1);
          for(;;) {
            pOt_y=(pOt_LONGREAL)(pOt_y*((pOt_LONGREAL)(10))+((pOt_LONGREAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5)))));
            pOt_j+=(1);
            if(( pOt_j==pOt_h)) break;
          }
          for(;;) {
            if(( pOt_j<pOt_i)); else break;
            pOt_g=(pOt_LONGREAL)(pOt_g/((pOt_LONGREAL)(10)));
            pOt_y=(pOt_LONGREAL)(((pOt_LONGREAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))))*pOt_g+pOt_y);
            pOt_j+=(1);
          }
          pOt_ReadScaleFactor_Scan_Texts();
          if(pOt_negE) {
            if(( pOt_e<=308)) {
              pOt_y=(pOt_LONGREAL)(pOt_y/pOt_TenL_Reals((pOt_INTEGER)(pOt_e)));
            } else {
              pOt_y=(pOt_LONGREAL)(0);
            }
          } else if(( pOt_e>((pOt_INTEGER)(0)))) {
            if(( pOt_e<=308)) {
              pOt_y=(pOt_LONGREAL)(pOt_TenL_Reals((pOt_INTEGER)(pOt_e))*pOt_y);
            } else {
              pOt__halt(__FILE__,__LINE__,40);
            }
          }
          if(pOt_neg) {
            pOt_y=(pOt_LONGREAL)(-pOt_y);
          }
          (*pOt_S).pOt_class=(pOt_INTEGER)(5);
          (*pOt_S).pOt_y=(pOt_LONGREAL)(pOt_y);
        } else {
          pOt_e=(pOt_INTEGER)(0);
          pOt_x=(pOt_REAL)(0);
          pOt_f=(pOt_REAL)(1);
          for(;;) {
            pOt_x=(pOt_REAL)(pOt_x*((pOt_REAL)(10))+((pOt_REAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5)))));
            pOt_j+=(1);
            if(( pOt_j==pOt_h)) break;
          }
          for(;;) {
            if(( pOt_j<pOt_i)); else break;
            pOt_f=(pOt_REAL)(pOt_f/((pOt_REAL)(10)));
            pOt_x=(pOt_REAL)(((pOt_REAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))))*pOt_f+pOt_x);
            pOt_j+=(1);
          }
          if(((unsigned char) pOt_ch==(unsigned char)'E')) {
            pOt_ReadScaleFactor_Scan_Texts();
          }
          if(pOt_negE) {
            if(( pOt_e<=((pOt_INTEGER)(38)))) {
              pOt_x=(pOt_REAL)(pOt_x/pOt_Ten_Reals((pOt_INTEGER)(pOt_e)));
            } else {
              pOt_x=(pOt_REAL)(0);
            }
          } else if(( pOt_e>((pOt_INTEGER)(0)))) {
            if(( pOt_e<=((pOt_INTEGER)(38)))) {
              pOt_x=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)(pOt_e))*pOt_x);
            } else {
              pOt__halt(__FILE__,__LINE__,40);
            }
          }
          if(pOt_neg) {
            pOt_x=(pOt_REAL)(-pOt_x);
          }
          (*pOt_S).pOt_class=(pOt_INTEGER)(4);
          (*pOt_S).pOt_x=(pOt_REAL)(pOt_x);
        }
        if(pOt_hex) {
          (*pOt_S).pOt_class=(pOt_INTEGER)(0);
        }
      } else {
        (*pOt_S).pOt_class=(pOt_INTEGER)(3);
        pOt_k=(pOt_LONGINT)(0);
        for(;;) {
          pOt_k=(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))),6));
          pOt_j+=(1);
          if(( pOt_j==pOt_i)) break;
        }
        if(pOt_neg) {
          (*pOt_S).pOt_i=(pOt_LONGINT)(-pOt_k);
        } else {
          (*pOt_S).pOt_i=(pOt_LONGINT)(pOt_k);
        }
        if(pOt_hex) {
          (*pOt_S).pOt_class=(pOt_INTEGER)(0);
        } else {
          (*pOt_S).pOt_class=(pOt_INTEGER)(3);
        }
      }
    } else {
      (*pOt_S).pOt_class=(pOt_INTEGER)(6);
      if(pOt_neg) {
        (*pOt_S).pOt_c='-';
      } else {
        (*pOt_S).pOt_c=pOt_ch;
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
      }
    }
  }
  (*pOt_S).pOt_nextCh=pOt_ch;

pOt__Epilogue:;
  pOt_S_Scan_Texts=pOt_S_;
  pOt_ch_Scan_Texts=pOt_ch_;
  pOt_term_Scan_Texts=pOt_term_;
  pOt_neg_Scan_Texts=pOt_neg_;
  pOt_negE_Scan_Texts=pOt_negE_;
  pOt_hex_Scan_Texts=pOt_hex_;
  pOt_i_Scan_Texts=pOt_i_;
  pOt_j_Scan_Texts=pOt_j_;
  pOt_h_Scan_Texts=pOt_h_;
  pOt_e_Scan_Texts=pOt_e_;
  pOt_k_Scan_Texts=pOt_k_;
  pOt_x_Scan_Texts=pOt_x_;
  pOt_f_Scan_Texts=pOt_f_;
  pOt_y_Scan_Texts=pOt_y_;
  pOt_g_Scan_Texts=pOt_g_;
  pOt_d_Scan_Texts=pOt_d_;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_OpenWriter_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W)
#else
  (pOt_W)
  struct pOt__tag_5_Texts *pOt_W;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_OpenBuf_Texts(&(*pOt_W).pOt_buf);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_Write_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_CHAR pOt_ch)
#else
  (pOt_W, pOt_ch)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_CHAR pOt_ch;

#endif
{
  pOt_Buffer_Texts pOt_B;
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
  struct {void *next, *vars[0x1];} pOt__gc_strs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__gc_strs.next = &pOt__gc_ptrs;
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
  pOt__gc_strs.vars[0x0]=pOt_NIL;
  pOt__gc_ptrs.vars[0x0]=&pOt_B;
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
  pOt_B=pOt_NIL;

  if(( (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_len==((pOt_LONGINT)(512)))) {
    pOt_OpenBuf_Texts(&pOt_B);
    (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,pOt_B))).pOt_next=(struct pOt__tag_1_Texts*)((*pOt_W).pOt_buf);
    (*pOt_W).pOt_buf=(struct pOt__tag_1_Texts*)(pOt_B);
  }
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_data.arr[pOt__inxchk(__FILE__,__LINE__,0x200, (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_len)]=pOt_ch;
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_len+=(1);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_WriteLn_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W)
#else
  (pOt_W)
  struct pOt__tag_5_Texts *pOt_W;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'\12');

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_WriteString_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt__DynArr *pOt_s)
#else
  (pOt_W, pOt_s)
  struct pOt__tag_5_Texts *pOt_W;
  pOt__DynArr *pOt_s;

#endif
{
  pOt_INTEGER pOt_i;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_i=(pOt_INTEGER)(0);
  for(;;) {
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))>=(unsigned char)' ')); else break;
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i))))));
    pOt_i+=(1);
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  pOt__rm_par((pOt__TypDsc**)pOt_s);
}


struct pOt__tag_7_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0xBL];
} ;
static pOt__ArrTypDsc pOt__td_7_Texts= {
  1,
  0xBL, sizeof(pOt_CHAR)
};


extern void pOt_WriteInt_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGINT pOt_x, pOt_LONGINT pOt_n)
#else
  (pOt_W, pOt_x, pOt_n)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_LONGINT pOt_x, pOt_n;

#endif
{
  pOt_INTEGER pOt_i;
  pOt_LONGINT pOt_x0;
  struct pOt__tag_7_Texts pOt_a;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__init_var((pOt__TypDsc**)&pOt_a,(pOt__TypDsc*)&pOt__td_7_Texts);

  pOt_i=(pOt_INTEGER)(0);
  if(( pOt_x<((pOt_LONGINT)(0)))) {
    if(( pOt_x==(pOt_LONGINT)0x80000000L)) {
      pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0xC]))));
      goto pOt__Epilogue;
    } else {
      pOt_n-=(1);
      pOt_x0=(pOt_LONGINT)(-pOt_x);
    }
  } else {
    pOt_x0=(pOt_LONGINT)(pOt_x);
  }
  for(;;) {
    pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xB, pOt_i)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x0),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(48),6)));
    pOt_x0=(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x0),(pOt_LONGINT)(10),6));
    pOt_i+=(1);
    if(( pOt_x0==((pOt_LONGINT)(0)))) break;
  }
  for(;;) {
    if(( pOt_n>((pOt_LONGINT)(pOt_i)))); else break;
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
    pOt_n-=(1);
  }
  if(( pOt_x<((pOt_LONGINT)(0)))) {
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
  }
  for(;;) {
    pOt_i-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xB, pOt_i)]);
    if(( pOt_i==((pOt_INTEGER)(0)))) break;
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_8_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0xAL];
} ;
static pOt__ArrTypDsc pOt__td_8_Texts= {
  1,
  0xAL, sizeof(pOt_CHAR)
};


extern void pOt_WriteHex_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGINT pOt_x)
#else
  (pOt_W, pOt_x)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_LONGINT pOt_x;

#endif
{
  pOt_INTEGER pOt_i;
  pOt_LONGINT pOt_y;
  struct pOt__tag_8_Texts pOt_a;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__init_var((pOt__TypDsc**)&pOt_a,(pOt__TypDsc*)&pOt__td_8_Texts);

  pOt_i=(pOt_INTEGER)(0);
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
  for(;;) {
    pOt_y=(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(16),6));
    if(( pOt_y<((pOt_LONGINT)(10)))) {
      pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xA, pOt_i)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_y),(pOt_LONGINT)(48),6)));
    } else {
      pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xA, pOt_i)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_y),(pOt_LONGINT)(55),6)));
    }
    pOt_x=(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(16),6));
    pOt_i+=(1);
    if(( pOt_i==((pOt_INTEGER)(8)))) break;
  }
  for(;;) {
    pOt_i-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xA, pOt_i)]);
    if(( pOt_i==((pOt_INTEGER)(0)))) break;
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_9_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x9L];
} ;
static pOt__ArrTypDsc pOt__td_9_Texts= {
  1,
  0x9L, sizeof(pOt_CHAR)
};


extern void pOt_WriteReal_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_REAL pOt_x, pOt_INTEGER pOt_n)
#else
  (pOt_W, pOt_x, pOt_n)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_REAL pOt_x;
  pOt_INTEGER pOt_n;

#endif
{
  pOt_INTEGER pOt_e;
  pOt_REAL pOt_x0;
  struct pOt__tag_9_Texts pOt_d;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_9_Texts);

  pOt_e=(pOt_INTEGER)(pOt_Expo_Reals((pOt_REAL)(pOt_x)));
  if(( pOt_e==((pOt_INTEGER)(0)))) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x14L],&pOt__str_td[0x3]))));
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
      pOt_n-=(1);
      if(( pOt_n<=((pOt_INTEGER)(3)))) break;
    }
  } else if(( pOt_e==255)) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1CL],&pOt__str_td[0x4]))));
    for(;;) {
      if(( pOt_n>((pOt_INTEGER)(4)))); else break;
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
      pOt_n-=(1);
    }
  } else {
    if(( pOt_n<=((pOt_INTEGER)(9)))) {
      pOt_n=(pOt_INTEGER)(3);
    } else {
      pOt_n-=(6);
    }
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
      pOt_n-=(1);
      if(( pOt_n<=((pOt_INTEGER)(8)))) break;
    }
    if(( pOt_x<(pOt_REAL)0.0)) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
      pOt_x=(pOt_REAL)(-pOt_x);
    } else {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
    }
    pOt_e=(pOt_INTEGER)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(127),5))),(pOt_LONGINT)(77),5)),(pOt_LONGINT)(256),5));
    if(( pOt_e>=((pOt_INTEGER)(0)))) {
      pOt_x=(pOt_REAL)(pOt_x/pOt_Ten_Reals((pOt_INTEGER)(pOt_e)));
    } else {
      pOt_x=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)(-pOt_e))*pOt_x);
    }
    if(( pOt_x>=(pOt_REAL)1.0000000E1)) {
      pOt_x=(pOt_REAL)((pOt_REAL)1.0000000E-1*pOt_x);
      pOt_e+=(1);
    }
    pOt_x0=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(1),5))));
    pOt_x=(pOt_REAL)(pOt_x0*pOt_x+(pOt_REAL)5.0000000E-1);
    if(( pOt_x>=(pOt_REAL)1.0000000E1*pOt_x0)) {
      pOt_x=(pOt_REAL)(pOt_x*(pOt_REAL)1.0000000E-1);
      pOt_e+=(1);
    }
    pOt_Convert_Reals((pOt_REAL)(pOt_x),(pOt_INTEGER)(pOt_n),(pOt__ArrTypDsc**)&pOt_d);
    pOt_n-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x9, pOt_n)]);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
    for(;;) {
      pOt_n-=(1);
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x9, pOt_n)]);
      if(( pOt_n==((pOt_INTEGER)(0)))) break;
    }
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'E');
    if(( pOt_e<((pOt_INTEGER)(0)))) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
      pOt_e=(pOt_INTEGER)(-pOt_e);
    } else {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'+');
    }
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_A_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x9L];
} ;
static pOt__ArrTypDsc pOt__td_A_Texts= {
  1,
  0x9L, sizeof(pOt_CHAR)
};

static struct pOt__tag_5_Texts *pOt_W_WriteRealFix_Texts;
static pOt_REAL (*pOt_x_WriteRealFix_Texts);
static pOt_INTEGER (*pOt_n_WriteRealFix_Texts), (*pOt_k_WriteRealFix_Texts), (*pOt_e_WriteRealFix_Texts), (*pOt_i_WriteRealFix_Texts);
static pOt_CHAR (*pOt_sign_WriteRealFix_Texts);
static pOt_REAL (*pOt_x0_WriteRealFix_Texts);
static struct pOt__tag_A_Texts (*pOt_d_WriteRealFix_Texts);

extern void pOt_WriteRealFix_Texts pOt__ARGS((struct pOt__tag_5_Texts *, pOt_REAL , pOt_INTEGER , pOt_INTEGER ));




static void pOt_seq_WriteRealFix_Texts
#if pOt__ANSI_C
  (pOt_CHAR pOt_ch, pOt_INTEGER pOt_n)
#else
  (pOt_ch, pOt_n)
  pOt_CHAR pOt_ch;
  pOt_INTEGER pOt_n;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  for(;;) {
    if(( pOt_n>((pOt_INTEGER)(0)))); else break;
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteRealFix_Texts),pOt_ch);
    pOt_n-=(1);
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




static void pOt_dig_WriteRealFix_Texts
#if pOt__ANSI_C
  (pOt_INTEGER pOt_n)
#else
  (pOt_n)
  pOt_INTEGER pOt_n;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  for(;;) {
    if(( pOt_n>((pOt_INTEGER)(0)))); else break;
    (*pOt_i_WriteRealFix_Texts)-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteRealFix_Texts),(*pOt_d_WriteRealFix_Texts).arr[pOt__inxchk(__FILE__,__LINE__,0x9, (*pOt_i_WriteRealFix_Texts))]);
    pOt_n-=(1);
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

extern void pOt_WriteRealFix_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_REAL pOt_x, pOt_INTEGER pOt_n, pOt_INTEGER pOt_k)
#else
  (pOt_W, pOt_x, pOt_n, pOt_k)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_REAL pOt_x;
  pOt_INTEGER pOt_n, pOt_k;

#endif
{
  struct pOt__tag_5_Texts *pOt_W_;
  pOt_REAL (*pOt_x_);
  pOt_INTEGER (*pOt_n_), (*pOt_k_), pOt_e, (*pOt_e_), pOt_i, (*pOt_i_);
  pOt_CHAR pOt_sign, (*pOt_sign_);
  pOt_REAL pOt_x0, (*pOt_x0_);
  struct pOt__tag_A_Texts pOt_d, (*pOt_d_);
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt_W_=pOt_W_WriteRealFix_Texts;
  pOt_W_WriteRealFix_Texts=pOt_W;
  pOt_x_=pOt_x_WriteRealFix_Texts;
  pOt_x_WriteRealFix_Texts=&pOt_x;
  pOt_n_=pOt_n_WriteRealFix_Texts;
  pOt_n_WriteRealFix_Texts=&pOt_n;
  pOt_k_=pOt_k_WriteRealFix_Texts;
  pOt_k_WriteRealFix_Texts=&pOt_k;
  pOt_e_=pOt_e_WriteRealFix_Texts;
  pOt_e_WriteRealFix_Texts=&pOt_e;
  pOt_i_=pOt_i_WriteRealFix_Texts;
  pOt_i_WriteRealFix_Texts=&pOt_i;
  pOt_sign_=pOt_sign_WriteRealFix_Texts;
  pOt_sign_WriteRealFix_Texts=&pOt_sign;
  pOt_x0_=pOt_x0_WriteRealFix_Texts;
  pOt_x0_WriteRealFix_Texts=&pOt_x0;
  pOt_d_=pOt_d_WriteRealFix_Texts;
  pOt_d_WriteRealFix_Texts=&pOt_d;
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_A_Texts);

  pOt_e=(pOt_INTEGER)(pOt_Expo_Reals((pOt_REAL)(pOt_x)));
  if(( pOt_k<((pOt_INTEGER)(0)))) {
    pOt_k=(pOt_INTEGER)(0);
  }
  if(( pOt_e==((pOt_INTEGER)(0)))) {
    pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(pOt_k),5)),(pOt_LONGINT)(2),5)));
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'0');
    pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(1),5)));
  } else if(( pOt_e==255)) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1CL],&pOt__str_td[0x4]))));
    pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(4),5)));
  } else {
    pOt_e=(pOt_INTEGER)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(127),5))),(pOt_LONGINT)(77),5)),(pOt_LONGINT)(256),5));
    if(( pOt_x<((pOt_REAL)(0)))) {
      pOt_sign='-';
      pOt_x=(pOt_REAL)(-pOt_x);
    } else {
      pOt_sign=' ';
    }
    if(( pOt_e>=((pOt_INTEGER)(0)))) {
      pOt_x=(pOt_REAL)(pOt_x/pOt_Ten_Reals((pOt_INTEGER)(pOt_e)));
    } else {
      pOt_x=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)(-pOt_e))*pOt_x);
    }
    if(( pOt_x>=(pOt_REAL)1.0000000E1)) {
      pOt_x=(pOt_REAL)((pOt_REAL)1.0000000E-1*pOt_x);
      pOt_e+=(1);
    }
    if(( (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5)>=((pOt_INTEGER)(8)))) {
      pOt_k=(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(9),(pOt_LONGINT)(1),4)),(pOt_LONGINT)(pOt_e),5));
    } else if(( (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5)<((pOt_INTEGER)(0)))) {
      pOt_k=(pOt_INTEGER)(-pOt_e);
      pOt_x=(pOt_REAL)((pOt_REAL)0.0);
    }
    pOt_x0=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5))));
    pOt_x=(pOt_REAL)(pOt_x0*pOt_x+(pOt_REAL)5.0000000E-1);
    if(( pOt_x>=(pOt_REAL)1.0000000E1*pOt_x0)) {
      pOt_e+=(1);
    }
    pOt_e+=(1);
    pOt_i=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5));
    pOt_Convert_Reals((pOt_REAL)(pOt_x),(pOt_INTEGER)(pOt_i),(pOt__ArrTypDsc**)&pOt_d);
    if(( pOt_e>((pOt_INTEGER)(0)))) {
      pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(pOt_e),5)),(pOt_LONGINT)(pOt_k),5)),(pOt_LONGINT)(2),5)));
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_sign);
      pOt_dig_WriteRealFix_Texts((pOt_INTEGER)(pOt_e));
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
      pOt_dig_WriteRealFix_Texts((pOt_INTEGER)(pOt_k));
    } else {
      pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(pOt_k),5)),(pOt_LONGINT)(3),5)));
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_sign);
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'0');
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
      pOt_seq_WriteRealFix_Texts('0',(pOt_INTEGER)(-pOt_e));
      pOt_dig_WriteRealFix_Texts((pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5)));
    }
  }

pOt__Epilogue:;
  pOt_W_WriteRealFix_Texts=pOt_W_;
  pOt_x_WriteRealFix_Texts=pOt_x_;
  pOt_n_WriteRealFix_Texts=pOt_n_;
  pOt_k_WriteRealFix_Texts=pOt_k_;
  pOt_e_WriteRealFix_Texts=pOt_e_;
  pOt_i_WriteRealFix_Texts=pOt_i_;
  pOt_sign_WriteRealFix_Texts=pOt_sign_;
  pOt_x0_WriteRealFix_Texts=pOt_x0_;
  pOt_d_WriteRealFix_Texts=pOt_d_;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_B_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x8L];
} ;
static pOt__ArrTypDsc pOt__td_B_Texts= {
  1,
  0x8L, sizeof(pOt_CHAR)
};


extern void pOt_WriteRealHex_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_REAL pOt_x)
#else
  (pOt_W, pOt_x)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_REAL pOt_x;

#endif
{
  pOt_INTEGER pOt_i;
  struct pOt__tag_B_Texts pOt_d;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_B_Texts);

  pOt_ConvertH_Reals((pOt_REAL)(pOt_x),(pOt__ArrTypDsc**)&pOt_d);
  pOt_i=(pOt_INTEGER)(0);
  for(;;) {
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x8, pOt_i)]);
    pOt_i+=(1);
    if(( pOt_i==((pOt_INTEGER)(8)))) break;
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_C_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x10L];
} ;
static pOt__ArrTypDsc pOt__td_C_Texts= {
  1,
  0x10L, sizeof(pOt_CHAR)
};


extern void pOt_WriteLongReal_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGREAL pOt_x, pOt_INTEGER pOt_n)
#else
  (pOt_W, pOt_x, pOt_n)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_LONGREAL pOt_x;
  pOt_INTEGER pOt_n;

#endif
{
  pOt_INTEGER pOt_e;
  pOt_LONGREAL pOt_x0;
  struct pOt__tag_C_Texts pOt_d;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_C_Texts);

  pOt_e=(pOt_INTEGER)(pOt_ExpoL_Reals((pOt_LONGREAL)(pOt_x)));
  if(( pOt_e==((pOt_INTEGER)(0)))) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x14L],&pOt__str_td[0x3]))));
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
      pOt_n-=(1);
      if(( pOt_n<=((pOt_INTEGER)(3)))) break;
    }
  } else if(( pOt_e==2047)) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1CL],&pOt__str_td[0x4]))));
    for(;;) {
      if(( pOt_n>((pOt_INTEGER)(4)))); else break;
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
      pOt_n-=(1);
    }
  } else {
    if(( pOt_n<=((pOt_INTEGER)(10)))) {
      pOt_n=(pOt_INTEGER)(3);
    } else {
      pOt_n-=(7);
    }
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
      pOt_n-=(1);
      if(( pOt_n<=((pOt_INTEGER)(16)))) break;
    }
    if(( pOt_x<((pOt_LONGREAL)(0)))) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
      pOt_x=(pOt_LONGREAL)(-pOt_x);
    } else {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
    }
    pOt_e=(pOt_INTEGER)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,(pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(1023),5))),(pOt_LONGINT)(77),6)),(pOt_LONGINT)(256),6)));
    if(( pOt_e>=((pOt_INTEGER)(0)))) {
      pOt_x=(pOt_LONGREAL)(pOt_x/pOt_TenL_Reals((pOt_INTEGER)(pOt_e)));
    } else {
      pOt_x=(pOt_LONGREAL)(pOt_TenL_Reals((pOt_INTEGER)(-pOt_e))*pOt_x);
    }
    if(( pOt_x>=1.000000000000000E1)) {
      pOt_x=(pOt_LONGREAL)(1.000000000000000E-1*pOt_x);
      pOt_e+=(1);
    }
    pOt_x0=(pOt_LONGREAL)(pOt_TenL_Reals((pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(1),5))));
    pOt_x=(pOt_LONGREAL)(pOt_x0*pOt_x+5.000000000000000E-1);
    if(( pOt_x>=1.000000000000000E1*pOt_x0)) {
      pOt_x=(pOt_LONGREAL)(1.000000000000000E-1*pOt_x);
      pOt_e+=(1);
    }
    pOt_ConvertL_Reals((pOt_LONGREAL)(pOt_x),(pOt_INTEGER)(pOt_n),(pOt__ArrTypDsc**)&pOt_d);
    pOt_n-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_n)]);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
    for(;;) {
      pOt_n-=(1);
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_n)]);
      if(( pOt_n==((pOt_INTEGER)(0)))) break;
    }
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'D');
    if(( pOt_e<((pOt_INTEGER)(0)))) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
      pOt_e=(pOt_INTEGER)(-pOt_e);
    } else {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'+');
    }
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(100),5)),(pOt_LONGINT)(48),5))));
    pOt_e=(pOt_INTEGER)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(100),5));
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}


struct pOt__tag_D_Texts {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x10L];
} ;
static pOt__ArrTypDsc pOt__td_D_Texts= {
  1,
  0x10L, sizeof(pOt_CHAR)
};


extern void pOt_WriteLongRealHex_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGREAL pOt_x)
#else
  (pOt_W, pOt_x)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_LONGREAL pOt_x;

#endif
{
  pOt_INTEGER pOt_i;
  struct pOt__tag_D_Texts pOt_d;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_D_Texts);

  pOt_ConvertHL_Reals((pOt_LONGREAL)(pOt_x),(pOt__ArrTypDsc**)&pOt_d);
  pOt_i=(pOt_INTEGER)(0);
  for(;;) {
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_i)]);
    pOt_i+=(1);
    if(( pOt_i==((pOt_INTEGER)(16)))) break;
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



static struct pOt__tag_5_Texts *pOt_W_WriteDate_Texts;
static pOt_LONGINT (*pOt_t_WriteDate_Texts), (*pOt_d_WriteDate_Texts);

extern void pOt_WriteDate_Texts pOt__ARGS((struct pOt__tag_5_Texts *, pOt_LONGINT , pOt_LONGINT ));




static void pOt_WritePair_WriteDate_Texts
#if pOt__ANSI_C
  (pOt_CHAR pOt_ch, pOt_LONGINT pOt_x)
#else
  (pOt_ch, pOt_x)
  pOt_CHAR pOt_ch;
  pOt_LONGINT pOt_x;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteDate_Texts),pOt_ch);
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteDate_Texts),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(48),6))));
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteDate_Texts),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(48),6))));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

extern void pOt_WriteDate_Texts
#if pOt__ANSI_C
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGINT pOt_t, pOt_LONGINT pOt_d)
#else
  (pOt_W, pOt_t, pOt_d)
  struct pOt__tag_5_Texts *pOt_W;
  pOt_LONGINT pOt_t, pOt_d;

#endif
{
  struct pOt__tag_5_Texts *pOt_W_;
  pOt_LONGINT (*pOt_t_), (*pOt_d_);
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt_W_=pOt_W_WriteDate_Texts;
  pOt_W_WriteDate_Texts=pOt_W;
  pOt_t_=pOt_t_WriteDate_Texts;
  pOt_t_WriteDate_Texts=&pOt_t;
  pOt_d_=pOt_d_WriteDate_Texts;
  pOt_d_WriteDate_Texts=&pOt_d;

  pOt_WritePair_WriteDate_Texts(' ',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_d),(pOt_LONGINT)(32),6)));
  pOt_WritePair_WriteDate_Texts('.',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_d),(pOt_LONGINT)(32),6)),(pOt_LONGINT)(16),6)));
  pOt_WritePair_WriteDate_Texts('.',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_d),(pOt_LONGINT)(512),6)),(pOt_LONGINT)(128),6)));
  pOt_WritePair_WriteDate_Texts(' ',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_t),(pOt_LONGINT)(4096),6)),(pOt_LONGINT)(32),6)));
  pOt_WritePair_WriteDate_Texts(':',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_t),(pOt_LONGINT)(64),6)),(pOt_LONGINT)(64),6)));
  pOt_WritePair_WriteDate_Texts(':',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_t),(pOt_LONGINT)(64),6)));

pOt__Epilogue:;
  pOt_W_WriteDate_Texts=pOt_W_;
  pOt_t_WriteDate_Texts=pOt_t_;
  pOt_d_WriteDate_Texts=pOt_d_;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_Open_Texts
#if pOt__ANSI_C
  (pOt_File_Files *pOt_T, pOt__DynArr *pOt_name)
#else
  (pOt_T, pOt_name)
  pOt_File_Files *pOt_T;
  pOt__DynArr *pOt_name;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  (*pOt_T)=(struct pOt__tag_1_Files*)(pOt_Old_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));
  if(( (*pOt_T)==pOt_NIL)) {
    (*pOt_T)=(struct pOt__tag_1_Files*)(pOt_New_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));
  }

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  pOt__rm_par((pOt__TypDsc**)pOt_name);
}




extern void pOt_Create_Texts
#if pOt__ANSI_C
  (pOt_File_Files *pOt_T, pOt__DynArr *pOt_name)
#else
  (pOt_T, pOt_name)
  pOt_File_Files *pOt_T;
  pOt__DynArr *pOt_name;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  (*pOt_T)=(struct pOt__tag_1_Files*)(pOt_New_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  pOt__rm_par((pOt__TypDsc**)pOt_name);
}




extern void pOt_Close_Texts
#if pOt__ANSI_C
  (pOt_File_Files pOt_T)
#else
  (pOt_T)
  pOt_File_Files pOt_T;

#endif
{
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
  struct {void *next, *vars[0x1];} pOt__gc_strs;
  pOt__gc_ptrs.next = pOt__gc_root;
  pOt__gc_strs.next = &pOt__gc_ptrs;
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
  pOt__gc_strs.vars[0x0]=pOt_NIL;
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;

  pOt_Close_Files((struct pOt__tag_1_Files*)(pOt_T));

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

void pOt_Texts__body()
{
  static int pOt_Texts__loaded=0;
  if(!pOt_Texts__loaded){
    pOt_Texts__loaded=1;

    pOt_Files__body();
    pOt_Reals__body();

    pOt__gc_ptrs.next=pOt__gc_root;
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;



  pOt__Epilogue:;
  }
}
