/* This code is generated by pOt. */

#include <pOtRTL.h>

#include "OS.hi"




static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
  pOt_NIL
}};
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
  pOt_NIL
}};




extern pOt_LONGINT pOt_Time_OS()
{
  pOt_LONGINT pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;


  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern void pOt_GetClock_OS
#if pOt__ANSI_C
  (pOt_LONGINT *pOt_date, pOt_LONGINT *pOt_time)
#else
  (pOt_date, pOt_time)
  pOt_LONGINT *pOt_date, *pOt_time;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_GetParFile_OS
#if pOt__ANSI_C
  (pOt__DynArr *pOt_fname)
#else
  (pOt_fname)
  pOt__DynArr *pOt_fname;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_GC_OS()
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

void pOt_OS__body()
{
  static int pOt_OS__loaded=0;
  if(!pOt_OS__loaded){
    pOt_OS__loaded=1;


    pOt__gc_ptrs.next=pOt__gc_root;
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;



  pOt__Epilogue:;
  }
}
