/* This code is generated by pOt. */

#include <pOtRTL.h>

#include "Reals.hi"




static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
  pOt_NIL
}};
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
  pOt_NIL
}};




extern pOt_INTEGER pOt_Expo_Reals
#if pOt__ANSI_C
  (pOt_REAL pOt_x)
#else
  (pOt_x)
  pOt_REAL pOt_x;

#endif
{
  pOt_INTEGER pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;


  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern pOt_INTEGER pOt_ExpoL_Reals
#if pOt__ANSI_C
  (pOt_LONGREAL pOt_x)
#else
  (pOt_x)
  pOt_LONGREAL pOt_x;

#endif
{
  pOt_INTEGER pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;


  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern void pOt_SetExpo_Reals
#if pOt__ANSI_C
  (pOt_INTEGER pOt_e, pOt_REAL *pOt_x)
#else
  (pOt_e, pOt_x)
  pOt_INTEGER pOt_e;
  pOt_REAL *pOt_x;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_SetExpoL_Reals
#if pOt__ANSI_C
  (pOt_INTEGER pOt_e, pOt_LONGREAL *pOt_x)
#else
  (pOt_e, pOt_x)
  pOt_INTEGER pOt_e;
  pOt_LONGREAL *pOt_x;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern pOt_REAL pOt_Ten_Reals
#if pOt__ANSI_C
  (pOt_INTEGER pOt_e)
#else
  (pOt_e)
  pOt_INTEGER pOt_e;

#endif
{
  pOt_REAL pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;


  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern pOt_LONGREAL pOt_TenL_Reals
#if pOt__ANSI_C
  (pOt_INTEGER pOt_e)
#else
  (pOt_e)
  pOt_INTEGER pOt_e;

#endif
{
  pOt_LONGREAL pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;


  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern void pOt_Convert_Reals
#if pOt__ANSI_C
  (pOt_REAL pOt_x, pOt_INTEGER pOt_n, pOt__DynArr *pOt_d)
#else
  (pOt_x, pOt_n, pOt_d)
  pOt_REAL pOt_x;
  pOt_INTEGER pOt_n;
  pOt__DynArr *pOt_d;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_ConvertL_Reals
#if pOt__ANSI_C
  (pOt_LONGREAL pOt_x, pOt_INTEGER pOt_n, pOt__DynArr *pOt_d)
#else
  (pOt_x, pOt_n, pOt_d)
  pOt_LONGREAL pOt_x;
  pOt_INTEGER pOt_n;
  pOt__DynArr *pOt_d;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_ConvertH_Reals
#if pOt__ANSI_C
  (pOt_REAL pOt_x, pOt__DynArr *pOt_d)
#else
  (pOt_x, pOt_d)
  pOt_REAL pOt_x;
  pOt__DynArr *pOt_d;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern void pOt_ConvertHL_Reals
#if pOt__ANSI_C
  (pOt_LONGREAL pOt_x, pOt__DynArr *pOt_d)
#else
  (pOt_x, pOt_d)
  pOt_LONGREAL pOt_x;
  pOt__DynArr *pOt_d;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}




extern pOt_LONGINT pOt_FSR_Reals()
{
  pOt_LONGINT pOt__retval;
  int pOt__gc_enabled_prev;
  pOt__gc_enabled_prev=pOt__gc_enabled;
  pOt__gc_enabled=0;


  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_enabled=pOt__gc_enabled_prev;
  return pOt__retval;
}




extern void pOt_SetFSR_Reals
#if pOt__ANSI_C
  (pOt_LONGINT pOt_status)
#else
  (pOt_status)
  pOt_LONGINT pOt_status;

#endif
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;


pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

void pOt_Reals__body()
{
  static int pOt_Reals__loaded=0;
  if(!pOt_Reals__loaded){
    pOt_Reals__loaded=1;


    pOt__gc_ptrs.next=pOt__gc_root;
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;



  pOt__Epilogue:;
  }
}
